#!/bin/bash



printf "Enter name of data file( sorry, I know I asked before): "
read $DATA

g++ -std=c++11 -o source Source.cpp Board.cpp
./source

printf "Choose graph view:\n1   Static view from top\n2   Dynamic view\n"

read VIEW

case $VIEW in

    1) #static topdown view

gnuplot -persist <<EOF
 set datafile separator " "
 unset key
 set view map
 xequiv = 1
 yequiv=1
 set size ratio -1
 set title "E Field"
 splot "$DATA" using 1:2:3 with points palette pointsize 3 pointtype 7

EOF

;;

    2) #dynamic graph

gnuplot -persist <<EOF
 set datafile separator " "
 unset key
 set title "E Field"
 xequiv = 1
 yequiv=1
 set size ratio -1
 splot "$DATA" using 1:2:3 with points palette pointsize 3 pointtype 7
 pause mouse close
EOF
;;

   *) #if other input, use dynamic graph (case 2)
gnuplot -persist <<EOF
 set datafile separator " "
 unset key
 set title "E Field"
 xequiv = 1
 yequiv=1
 splot "$DATA" using 1:2:3 with points palette pointsize 3 pointtype 7
 pause mouse close
EOF

;;
esac
